services:
  nginx:
    image: nginx:alpine
    ports:
      - "1027:80"
    depends_on:
      - wordpress
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf 
      - wordpress:/var/www/wordpress
    # networks:
    #   - backend

  wordpress:
    image:  wordpress:alpine
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress

  # php:
  #   image: php:fpm-alpine
  #   volumes:
  #     -  ./requirements/php/index.php:/var/www/html/index.php
  #   # networks:
  #   #   - backend

volumes:
  db_data:

networks:
  backend:

  # db:
  #   image: mariadb:latest
  #   volumes:
  #     - db_data:/var/lib/mysql
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=somewordpress
  #     - MYSQL_DATABASE=wordpress
  #     - MYSQL_USER=wordpress
  #     - MYSQL_PASSWORD=wordpress
  #   expose:
  #     - 3306
  #   networks:
  #     - backend