services:
  mariadb:
    container_name: mariadb-run
    build:
      context: requirements/mariadb
    env_file:
      - .env
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    expose:
      - 3306

  wordpress:
    container_name: wp-run
    build:
      context: requirements/wordpress
    env_file:
      - .env
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb-run
    networks:
      - inception
    expose:
      - 9000

  nginx:
    container_name: nginx-run
    build:
      context: requirements/nginx
    env_file:
      - .env
    restart: always
    volumes:
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/nginx.conf 
      - wordpress:/var/www/html/wordpress
    depends_on:
      - mariadb
      - wordpress
    networks:
      - inception
    ports:
      - 443:443


volumes:
  mariadb_data:
  wordpress:
  # o que colocar aqui

networks:
  inception:
