services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: always
    volumes:
      - mariadb_volume:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception
    expose:
      - 3306

  wordpress:
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - WORDPRESS_DATABASE=${WORDPRESS_DATABASE}
        - WORDPRESS_USER=${WORDPRESS_USER}
        - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    expose:
      - 9000

  nginx:
    container_name: nginx
    build:
      context: requirements/nginx
    restart: always
    ports:
      - 443:443
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www/html

networks:
  inception:

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/brunrodr/data/mariadb

  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/brunrodr/data/wordpress




