services:
  nginx:
    image: nginx:alpine
    ports:
      - "1027:80"

    volumes:
      - /home/bruno/Documents/42SP/13.Inception/Inception-git/srcs/requirements/nginx/conf/nginx.conf 
    depends_on:
      - php
    networks:
      - backend

  db:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
    networks:
      - backend

  php:
    image: php:fpm-alpine
    volumes:
      -  /home/bruno/Documents/42SP/13.Inception/Inception-git/srcs/requirements/php/index.php
      # - /var/www/html
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
